git remote add Legendorik         https://github.com/Legendorik/spbetu_metrology_2022_8304.git          # Алтухов    
git remote add artbutko           https://github.com/artbutko/spbetu_metrology_2022_8304.git            # Бутко      
git remote add UTHawk             https://github.com/UTHawk/spbetu_metrology_2022_8304.git              # Бочаров    
git remote add StiXs221           https://github.com/StiXs221/spbetu_metrology_2022_8304.git            # Воропаев   
git remote add scissorsnatcher    https://github.com/scissorsnatcher/spbetu_metrology_2022_8304.git     # Ивченко    
git remote add dnlka              https://github.com/dnlka/spbetu_metrology_2022_8304.git               # Кирьянов   
git remote add DanMsl             https://github.com/DanMsl/spbetu_metrology_2022_8304.git              # Масалыкин  
git remote add MatrosovDenis      https://github.com/MatrosovDenis/spbetu_metrology_2022_8304.git       # Матросов   
git remote add olga-alexandrovnaa https://github.com/olga-alexandrovnaa//spbetu_metrology_2022_8304.git # Мельникова 
git remote add Heliconter         https://github.com/Heliconter/spbetu_metrology_2022_8304.git          # Мешков     
git remote add mukhamux           https://github.com/mukhamux/spbetu_metrology_2022_8304.git            # Мухин      
git remote add NamYoSeb           https://github.com/NamYoSeb/spbetu_metrology_2022_8304.git            # Нам Е      
git remote add Nyashechka         https://github.com/Nyashechka/spbetu_metrology_2022_8304.git          # Николаева  
git remote add denisptuhov        https://github.com/denisptuhov/spbetu_metrology_2022_8304.git         # Птухов     
git remote add AlexRyzhickov      https://github.com/AlexRyzhickov/spbetu_metrology_2022_8304.git       # Рыжиков    
git remote add sidtheslooth20     https://github.com/sidtheslooth20/spbetu_metrology_2022_8304.git      # Самакаев   
git remote add sanizayyad         https://github.com/sanizayyad/spbetu_metrology_2022_8304.git          # Сани       
git remote add pseusys            https://github.com/pseusys/spbetu_metrology_2022_8304.git             # Сергеев    
git remote add gagask             https://github.com/gagask/spbetu_metrology_2022_8304.git              # Холковский 
git remote add Wintari            https://github.com/Wintari/spbetu_metrology_2022_8304.git             # Чешуин     
git remote add AleksandrShuka     https://github.com/AleksandrShuka/spbetu_metrology_2022_8304.git      # Щука       
git remote add Pirozhochek        https://github.com/Pirozhochek/spbetu_metrology_2022_8304.git         # Ястребов   
