#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
#git remote add                      https://github.com//spbetu_metrology_2022_8304.git
